<html>
    <head>
        <title>{{$car->title}}</title>
    </head>
    <body>
            <div>
                <h1>{{$car->title}}</h1>
                <p>{{$car->producer}}</p>
                <p>{{$car->number_of_doors}}</p>
            </div>
    </body>
</html>